// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nunmjfjjlcwrrtrppljv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51bm1qZmpqbGN3cnJ0cnBwbGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDg4MDgsImV4cCI6MjA2NTU4NDgwOH0.7Rog4jGeNsbpv_cCTrGemYrmIFpUXEGQESrVY0UAnto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);